default_language_version:
  python: python3.12

files: |  # python regex
  (?x)      # verbose regex
  ^(?:      # start of filename
    lib/.*  # all working python
    |
    [^/]+   # top level files
  )$        # end of filename


repos:
  - repo: meta
    hooks:
      - id: identity

  - repo: local
    hooks:
      - id: check-debug-notes
        name: Check DOCSTRING_DEBUG_NOTES is disabled
        description: Check if `DOCSTRING_DEBUG_NOTES` option in `config.py` is disabled.
        entry: bash
        language: system
        files: 'lib/freecad_stub_gen/config.py'
        args:
          - -c
          - |
            IS_ENABLED=$(
              grep --regexp "DOCSTRING_DEBUG_NOTES" \
                lib/freecad_stub_gen/config.py \
                | grep --regexp "False"
            )
            if [[ -z "${IS_ENABLED}" ]]; then
              echo "Error: DOCSTRING_DEBUG_NOTES is enabled in config.py"
              exit 1
            fi

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-yaml
      - id: check-toml
      - id: check-ast
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.24.1
    hooks:
      - id: validate-pyproject

  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix

  - repo: https://github.com/adhtruong/mirrors-typos
  # original repo: https://github.com/crate-ci/typos
  # we use mirror repo, because tags in original repo are broken:
  # https://github.com/crate-ci/typos/issues/390
    rev: v1.34.0
    hooks:
      - id: typos
        name: typos-diff
        args:
          - --diff
        verbose: true
      - id: typos
        name: typos-fix

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        additional_dependencies: [ tomli ]

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.22
    hooks:
      - id: mdformat
        additional_dependencies:
          # plugins to format for GitHub:
          - mdformat-gfm
          - mdformat-frontmatter
          - mdformat-footnote
          # plugin to format code blocks using `black` formatter:
          - mdformat-black
        args: [ --number ]

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: 0.3.4
    hooks:
      - id: auto-walrus
        args: [ --line-length=89 ]

  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.2
    hooks:
      - id: ruff
        name: ruff-diff
        args: [ --exit-non-zero-on-fix, --diff ]

      - id: ruff
        name: ruff-show-fixes
        args: [ --exit-non-zero-on-fix, --show-fixes ]

      - id: ruff
        name: ruff-auto-fix
        args: [ --exit-non-zero-on-fix, --fix ]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.402
    hooks:
      - id: pyright

#  - repo: local
#    hooks:
#      - id: mypy-local
#        name: Mypy local
#        description:
#          Install current package in editable mode and then run mypy.
#          The installation is required, because mypy is unable to use stub only
#          packages pointed by `mypy_path`.
#        entry: bash -x -c 'pip install --editable .[all]  && mypy'
#        language: python
#        types: [ python ]
#        pass_filenames: false
#        verbose: true
#        additional_dependencies:
#          - mypy==1.6.1
#        args:
#          - --strict
#          - --always-true=PYQT5
#          - --always-false=PYSIDE2
#          - --always-false=PYQT6
#          - --always-false=PYSIDE6

ci:
  autoupdate_schedule: quarterly
  skip:
    - pyright # https://github.com/RobertCraigie/pyright-python/issues/164
